## docker-compose.yml

services:
  redis:               ## Redis Replica
    image: redis:7
    container_name: redis-replica
    command: redis-server /etc/redis.conf
    volumes:
      - ./redis-replica.conf:/etc/redis.conf
      - ./data:/data
    ports:
      - "6379:6379"

  sentinel:            ## Redis Sentinel
    image: redis:7
    container_name: redis-sentinel
    command: redis-sentinel /etc/sentinel.conf
    volumes:
      - ./sentinel.conf:/etc/sentinel.conf
      - ./sentinel-data:/data
    ports:
      - "26379:26379"
