## docker-compose.yml
services:
  redis-1:
    image: redis:7
    container_name: redis-1
    command: redis-server /etc/redis.conf --port 7001 --cluster-announce-port 7001 --cluster-announce-bus-port 17001
    volumes:
      - ./redis.conf:/etc/redis.conf
      - ./7001:/data
    ports:
      - "7001:7001"
      - "17001:17001"

  redis-2:
    image: redis:7
    container_name: redis-2
    command: redis-server /etc/redis.conf --port 7002 --cluster-announce-port 7002 --cluster-announce-bus-port 17002
    volumes:
      - ./redis.conf:/etc/redis.conf
      - ./7002:/data
    ports:
      - "7002:7002"
      - "17002:17002"

  redis-3:
    image: redis:7
    container_name: redis-3
    command: redis-server /etc/redis.conf --port 7003 --cluster-announce-port 7003 --cluster-announce-bus-port 17003
    volumes:
      - ./redis.conf:/etc/redis.conf
      - ./7003:/data
    ports:
      - "7003:7003"
      - "17003:17003"

  redis-4:
    image: redis:7
    container_name: redis-4
    command: redis-server /etc/redis.conf --port 7004 --cluster-announce-port 7004 --cluster-announce-bus-port 17004
    volumes:
      - ./redis.conf:/etc/redis.conf
      - ./7004:/data
    ports:
      - "7004:7004"
      - "17004:17004"

  redis-5:
    image: redis:7
    container_name: redis-5
    command: redis-server /etc/redis.conf --port 7005 --cluster-announce-port 7005 --cluster-announce-bus-port 17005
    volumes:
      - ./redis.conf:/etc/redis.conf
      - ./7005:/data
    ports:
      - "7005:7005"
      - "17005:17005"

  redis-6:
    image: redis:7
    container_name: redis-6
    command: redis-server /etc/redis.conf --port 7006 --cluster-announce-port 7006 --cluster-announce-bus-port 17006
    volumes:
      - ./redis.conf:/etc/redis.conf
      - ./7006:/data
    ports:
      - "7006:7006"
      - "17006:17006"

