## docker-compose.yml

services:
  sentinel:             ## Redis Sentinel
    image: redis:7
    container_name: redis-sentinel
    command: redis-sentinel /etc/sentinel.conf
    volumes:
      - ./sentinel.conf:/etc/sentinel.conf
      - ./sentinel-data:/data
    ports:
      - "26379:26379"
