## docker-compose.yml

services:
  redis-3:
    image: redis:7
    container_name: redis-3
    command: redis-server /etc/redis.conf --port 7003 --cluster-announce-ip 192.168.10.193 --cluster-announce-port 7003 --cluster-announce-bus-port 17003
    volumes:
      - ./redis.conf:/etc/redis.conf
      - ./data/7003:/data
    ports:
      - "7003:7003"
      - "17003:17003"

  redis-5:
    image: redis:7
    container_name: redis-5
    command: redis-server /etc/redis.conf --port 7005 --cluster-announce-ip 192.168.10.193 --cluster-announce-port 7005 --cluster-announce-bus-port 17005
    volumes:
      - ./redis.conf:/etc/redis.conf
      - ./data/7005:/data
    ports:
      - "7005:7005"
      - "17005:17005"

